### PR TITLE
Adding configuration to PSU CAD

### PR DESCRIPTION
**Pull request by Garth-42**
Adding mouser part PSH configuration (alt part in shopping list) to CAD file. This requires 2x M4 8mm button head screws from the 2x M3 10mm flathead.

### CODE REVIEW

**Comment by Poofjunior** [comment]
Thanks for the changes!

I took a look, and it looks like I'm a bit behind in Solidworks versions. What version was this part made in? These days, Jubilee is on 2019, but I can (and eventually should) bump the project forward to the 2021 version that I've been avoiding upgrading to.

**Comment by Garth-42** [comment]
Hi Poof, glad to contribute to the project, even if it is in a small way. I am using Solidworks 2020 right now. Yup I saw it was 2019 and figured this would be a potential issue. When are you planning on bumping to 2021?

**Comment by Poofjunior** [comment]
My original plan was to linger about a year behind on versions since I can't always assume folks are working from the latest-and-greatest. All that said, sticking around in 2019 hasn't been an issue until now. Is there a really good reason to bump up to 2021 now?

It looks like I can open and view 2020-version parts, but not edit them. In that case, I'd be OK with merging this in for authorship on your end, folding the changes into the 2019 version, and then bringing the project up to 2020 in the next release or two. Otherwise, we can wait, and I can bump the project into 2020 first. Let me know what you think!

Long-term, I do want to explore the upcoming [Solidworks for Makers](https://discover.solidworks.com/3dexperience-solidworks-makers-available-2nd-half-2021) subscription offering to see if that's a more sustainable route for folks to contribute. (Hey, $9.99 a month is not bad!) It's not out just yet, but hopefully will emerge in the next month or two.

**Comment by Garth-42** [comment]
Meh, I don’t think there’s much of a reason to upgrade right now. It’s your call on whether you want to wait or not, I don’t want to make you roll in the changes to 2019, I am sure you have better things to do.

Solidworks for Makers is exciting! If that happens then I can roll my changes over into that.

**Pull request closed without merging**
