### PR TITLE
Beta version of Duet3 files

### PR DESCRIPTION
**Pull request by erikmcclain**
Orignal Authors Joshua Vasquez for Duet 2 and Danal to Duet 3

### CODE REVIEW

**Comment by Poofjunior** [comment]
This looks great. Just a couple questions beforehand. 

Why does **Toffsets.g** look like **tpost0.g**?

Also thanks for working back and forth with the terminal lug. I meant to fiddle with this value and haven't had the time to calibrate it.

**Comment by erikmcclain** [comment]
I honestly have no idea,  I tried to go in and fix it and thing I messed something up... I will have to check it out later.

That said good catch there should only be tool offsets in that file.  I have no idea how that gcode ended up in toffsets its not like that on my machine,  I must have fat fingered it at some point and fixed it but I dont remember doing it :/

**Comment by Poofjunior** [comment]
No worries. Apart from that, I think we're pretty close to a merge. Go ahead and tweak that offsets file, and we should be good to go.

**Comment by erikmcclain** [comment]
I think it should be good now if you want to double check.

**Pull request merged**
