### PR TITLE
Limit switches should use gnd + io

### PR DESCRIPTION
**Pull request by olby**

### CODE REVIEW

**Comment by olby** [comment]
The wiring diagram for duet3 had limit switches connected between 3.3v and io not gnd and io. The wiki has been updated with the digram changes in this pull.

**Comment by Poofjunior** [comment]
Thanks for the revision. Just to be clear, that's this update here?

image

**Comment by olby** [comment]
Replaced the outdated html with a svg that, I assume, can be used directly as img on the wiki. The svg is a fair bit smaller than the png generated from draw.io. (and yes, it is the update from the image in your comment)

**Comment by Poofjunior** [comment]
Thanks for the update! I'll see if the wiki is happy with rendering SVGs, but it shouldn't be an issue. Worst case: we can just make a png.

**Pull request merged**
